name: rivership
description: An opinionated infrastructure package for use with hooks_riverpod.
version: 0.1.2
repository: https://github.com/whynotmake-it/rivership/tree/main/packages/rivership
homepage: https://whynotmake.it

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ">=0.20.5 < 0.21.0"
  hooks_riverpod: ">= 2.5.1 < 3.0.0"
  intl: ">= 0.19.0 < 0.20.0"
  material_color_utilities: ">= 0.8.0 < 0.12.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lintervention: ^0.1.1
  mocktail: ^1.0.3
  rivership_test: ^0.1.0+2
